#!/bin/bash
if [ -z $1 ]; then
    cat - | curl -H "Content-Type: text/plain" --data-binary @- http://drup.semicolon.ca:5001
else
    curl -H "Content-Type: text/plain" --data-binary @$1 http://drup.semicolon.ca:5001
fi
